# Site settings
title: iOS blabla Design blabla Swift
email: m@itchingpixels.com
description: > # obviously.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: itchingpixels
github_username:  itchingpixels

# Build settings
markdown: kramdown
